zuul:
  host:
   connect-timeout-millis: 600000
   socket-timeout-millis: 600000
  routes:
    paas:
      sensitiveHeaders:
      url: ${openshift.url}
    uaa:
      sensitiveHeaders:
      url: ${qy-auth.url}/uaa
    caas-service:
      sensitiveHeaders:
      url: http://192.168.1.98:8807
    caas-helm:
      url: http://192.168.1.168:30188
    iaas-service:
      sensitiveHeaders:
      url: http://localhost:8810
    qy-iaas:
      sensitiveHeaders:
      url: http://192.168.1.106:8080
    qy-task:
      sensitiveHeaders:
      url: http://192.168.1.106:8081
    pservice:
      sensitiveHeaders:
      url: http://localhost:8082
    monitor:
      sensitiveHeaders:
      url: http://192.168.1.94:48504
  add-proxy-headers: true
  ignored-headers: Access-Control-Allow-Origin,
                   Access-Control-Allow-Methods,
                   Access-Control-Allow-Headers,
                   Access-Control-Max-Age


ribbon:
  eureka:
    enabled: false

server:
  port: 8080

openshift:
  url: https://192.168.1.168:8443

qy-auth:
  url: http://192.168.1.97:9999
security:
  basic:
    enabled: false
  oauth2:
    resource:
      id: service
      user-info-uri: ${qy-auth.url}/uaa/user
    client:
      accessTokenUri: http://localhost:${server.port}/uaa/oauth/token
      userAuthorizationUri: /uaa/oauth/authorize
      clientId: qy-client
      clientSecret: 123456
  ignored: /uaa/**

logging:
  level:
    org.springframework.security: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8801/eureka/
spring:
 http:
  multipart:
   max-file-size: '1024MB'
   max-request-size: '1024MB'